apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    app: nodejs
  template:
    metadata:
      name: nodejs
      labels:
        app: nodejs
    spec:
      containers:
      - name: node-kubernetes
        image: nodejs
        ports:
        - containerPort: 8080
